spartacus/spartacus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from text_search import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^registration/$', views.user_registration, name='user_registration'),
    url(r'^new_book/$', views.new_book, name='new_book'),
    url(r'^book-list/', views.book_list, name='book_list'),
    url(r'^text-search/', include('text_search.urls', namespace='text-search')),
    url(r'^pdf-to-text/', views.pdf_to_text_view, name='pdf_to_text'),
    url(r'^download-book/', views.download_book, name='download_book'),
    url(r'^login/', views.user_login, name='user_login'),
    url(r'^logout/', views.user_logout, name='user_logout'),
]

admin.site.site_header = 'SPARTACUS ADMIN'

spartacus/text_search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    auther = models.CharField(max_length=120, blank=True)
    file_name = models.CharField(max_length=120, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title


class BookPage(models.Model):
    book = models.ForeignKey(Book)
    number = models.IntegerField(default=0)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s Page %s' % (self.book.title, self.number)

    def __unicode__(self):
        return '%s Page %s' % (self.book.title, self.number)

spartacus/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- This is custom css -->
    <link href="{% static 'dist/css/custom.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block content %}

    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'dist/js/jquery-2.2.0.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    {% block script %}

    {% endblock %}
  </body>
</html>

spartacus/templates/book_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load category_filter %}
{% block container %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Category</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Uploaded</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for book in book_list %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.category.name }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.auther }}</td>
                            <td><a href="/download-book/?book_id={{ book.id }}">{{ book.file_name }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

spartacus/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load category_filter %}

{% block title %} Spartacus Text Search Application {% endblock %}

{% block content %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">SPARTACUS</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">Category<span class="caret"></span></a>
        <ul class="dropdown-menu">
          {% for category in category_list|category_list %}
          <li><a href="/book-list/?category_id={{ category.id }}">{{ category.name }}</a></li>
          {% endfor %}
        </ul>
      </li>
      <li><a href="/new_book/">Upload Document</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    </ul>
  </div>
</nav>

{% block container %}
<form id="id_search_form" method="get" action="/pdf-to-text/">{% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
    		<h2>Enter the keyword</h2>
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control input-lg" value="{{ request.GET.q }}" name="q" id="q" placeholder="Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
	</div>
	<div class="row">
	    <div class="col-sm-8 col-sm-offset-2">
            <div class="checkbox-inline"><label><input type="checkbox" id="id_synonyms" name="synonyms">Synonyms</label></div>
            <div class="checkbox-inline"><label><input type="checkbox" id="id_antonyms" name="antonyms">Antonyms</label></div>
            <div class="checkbox-inline">Category: <select id="id_category" name="category">
                <option value="0">Select</option>
            {% for category in category_list|category_list %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
			</select></div>
            <div class="checkbox-inline">Document: <select id="id_book" name="book">
                <option value="0">Select</option>
			</select></div>
        </div>
    </div>
</div>
</form>
{% endblock %}
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        var book_list = {{ book_list | safe }}
        $('#id_category').on('change', function() {
            var bookObj = $('#id_book'), cat=$(this);
            $(bookObj).html('');
            $(bookObj).append($('<option value="0">Select</option>'));
            $.each(book_list, function(index, item) {
                if (parseInt($(cat).val()) === item.category_id) {
                    var opt = $('<option value="'+ item.id +'">' + item.title + '</option>');
                    $(bookObj).append($(opt));
                }
            });
        });
       $('#id_search_form').on('submit', function() {
           var search = '', url, is_synonyms = 0, is_antonyms = 0, category_id = '', book_id='';
           search = $('#q').val().trim();
           category_id = parseInt($('#id_category').val());
           book_id = parseInt($('#id_book').val());
           is_synonyms = $('#id_synonyms').is(':checked') ? 1 : 0;
           is_antonyms = $('#id_antonyms').is(':checked') ? 1 : 0;
           var error = false, msg='';

           if (!error && search.length === 0) {
               error = true;
               msg = 'Please enter keyword';
           }

           if (!error && category_id === 0) {
               error = true;
               msg = 'Please select category'
           }

           if (!error && book_id === 0) {
               error = true;
               msg = 'Please select book'
           }

           if (!error) {
               url = '/pdf-to-text/?q=' + search + '&is_synonyms=' + is_synonyms + '&is_antonyms=' + is_antonyms;
               url += '&category_id=' + category_id + '&book_id=' + book_id;
              window.location.href = url;
           } else {
               alert(msg);
           }
          return false
       });
    });
</script>
{% endblock %}

spartacus/templates/new_book.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load category_filter %}
{% block container %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form method="post" action="/new_book/" enctype="multipart/form-data">{% csrf_token %}
            <div class="new-book-page">
                <div class="row">
                    <div class="col-sm-12 text-center">
                        {% if error %}
                            <span style="color: red">{{ msg }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <h4>Upload New Document</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <select class="form-control" name="category">
                            <option value="">Select Category</option>
                            {% for category in category_list|category_list %}
                            {% if doc_category == category.id %}
                             <option value="{{ category.id }}" selected>{{ category.name }}</option>
                            {% else %}
                             <option value="{{ category.id }}">{{ category.name }}</option>
                             {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <input type="text" name="document_title" class="form-control" placeholder="Document Title" value="{{ document_title }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <input type="text" name="document_auther" class="form-control" placeholder="Document Auther (Optional)" value="{{ document_auther }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <label for="exampleInputFile">Upload Document</label>
                        <input type="file" class="form-control-file" name="document_file"  aria-describedby="fileHelp">
                        <small id="fileHelp" class="form-text text-muted">The document file should be in pdf format.</small>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

spartacus/templates/pdf_to_text.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load category_filter %}
{% block container %}
<div class="container">
    <div class="row">
        <div class="col-sm-12"><strong>Total Pages:</strong> {{ pages }} <strong>Searched Keyword:</strong> {{ query }} {% if total_antonyms %}<strong>Antonyms:</strong> {{ total_antonyms }} {% endif %}
            {% if total_synonyms %}<strong>Synonyms:</strong> {{ total_synonyms }} {% endif %}</div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel-group">
                {% if result %}
                    {% for page in result %}
                        <div class="panel panel-primary">
                            <div class="panel-heading">{{ page.page }} Keywords: {{ page.search_keyword }}</div>
                            <div class="panel-body">{{ page.data | safe }}</div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div>Keyword not found...</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}